### ISSUE TITLE
Build 1.14.8 (60) crashes on startup on iPad 2

### ISSUE THREAD

**Issue by abacabadabacaba** [singalen/wesnoth#102]
The new build, 1.14.8 (60), crashes on startup on iPad 2 (iOS 9.3.5). The previous build, 1.14.8 (58), doesn't crash.

**Comment by singalen** [comment]
Thanks!
Do you crash reports sharing enabled?
I know it's not always working, but just maybe.

**Comment by abacabadabacaba** [comment]
I have installed the app through TestFlight. I don't see any crash-related options there.

**Comment by singalen** [comment]
It's in the regular options: https://support.apple.com/en-us/HT202100

**Comment by abacabadabacaba** [comment]
Yes, crash report sharing is enabled there.
Also, looking through the list of available log files, I don't see any related to the Battle for Wesnoth app. So maybe it's not a regular crash but the app runs out of memory or something like that.

**Comment by singalen** [comment]
Now that I think of it, it should be the new GUI making an exit.
Should be reproducible in a simulator then.

**Comment by singalen** [comment]
Please try the today's TF.
