### ISSUE TITLE
Build 1.14.8 (67) crashes on startup

### ISSUE THREAD

**Issue by abacabadabacaba** [singalen/wesnoth#107]
Tested on two devices: iPad 2 (iOS 9.3.5) and iPhone 4S (iOS 9.3.6). On both, the game crashes during early loading stage, when only the logo is shown.

**Comment by singalen** [comment]
Thanks for reporting!

**Comment by singalen** [comment]
Wait a moment, 4S? Wow, I thought I had old hardware...
4S is not supported, I'm afraid, sorry! The smallest screen this version supports is 5, which is 320x568. I'll see what I can do, but don't expect much. It's already barely usable: https://forums.wesnoth.org/viewtopic.php?f=2&t=51114

iPad 2, OTOH, should have been fine, it's got a honest 1024x768 resolution... unless SDL is acting funny.

**Comment by singalen** [comment]
I guess I found it, it happened when iCloud was disabled for an app. Publishing a new beta soon.
Should work on iPhone 4S as well, though, it's still barely usable. Thanks for testing!

**Comment by abacabadabacaba** [comment]
Build 1.14.8 (69) launches without crashing on the iPhone, but still crashes on the iPad. The cause is probably different this time, because it only crashes when it is about to show the main menu.

**Comment by singalen** [comment]
Please try today's TF.
