### ISSUE TITLE
Battery level doesn't update

### ISSUE THREAD

**Issue by abacabadabacaba** [singalen/wesnoth#110]
iPad 2, iOS 9.3.5, build 1.14.8 (70).

The game interface shows the current battery level on the top panel. However, it is never updated.

**Comment by singalen** [comment]
Ouch, that's a shame.

**Comment by singalen** [comment]
On older devices, [battery level is reported with 5% granularity](https://stackoverflow.com/questions/11807295/how-to-get-real-time-battery-level-on-ios-with-a-1-granularity). Let me make sure it's not the case.

**Comment by singalen** [comment]
Fixed in 1.14.8.
