### ISSUE TITLE
Enemy units do not have an orb

### ISSUE THREAD

**Issue by SleepyHead32** [singalen/wesnoth#16]
Normally they would have a red orb but they are missing one.

**Comment by Simon-Laux** [comment]
#17 is the same issue.
you can change the color of the orbs since the newer versions.
![image](https://user-images.githubusercontent.com/18725968/28851819-5f5553b8-7725-11e7-8447-7f566e0c4967.png)

**Comment by singalen** [comment]
Thanks!
