### ISSUE TITLE
Player's units have wrong colored orbs

### ISSUE THREAD

**Issue by SleepyHead32** [singalen/wesnoth#17]
Normally a unit with no movement points left has a black orb but right now it's has a red orb.

**Comment by Simon-Laux** [comment]
i think there are settings for that, that change is not only in the iOS version.

**Comment by Simon-Laux** [comment]
![image](https://user-images.githubusercontent.com/18725968/28851819-5f5553b8-7725-11e7-8447-7f566e0c4967.png)
I just wonder if preferences get saved yet

**Comment by singalen** [comment]
Wow. Who even needed that feature?

**Comment by Simon-Laux** [comment]
I think it comes from here: https://forums.wesnoth.org/viewtopic.php?f=12&t=39570
