### ISSUE TITLE
Show battery level while playing

### ISSUE THREAD

**Issue by abacabadabacaba** [singalen/wesnoth#23]

**Comment by singalen** [comment]
Hmm. Useful, but where?

**Comment by abacabadabacaba** [comment]
I think that a good place is in the top row, next to the current time. Generally, the users will expect to find it somewhere near top right corner, where it is displayed normally. We just need an icon for it that will fit in the overall style.

**Comment by abacabadabacaba** [comment]
I also think that adding battery level indication may be good for desktop version as well, given that it is used on laptops.

**Comment by ghost** [comment]
I agree batt indicator next to clock, if introducing it is not a cause for bigger problems. Maybe optional is better than permanent.

**Comment by singalen** [comment]
There is a support for battery widget in Wesnoth.
The mainline may remove it soon, though.
The newer iOS has a pull-down (or pull-up) screen with a clock and a battery, so it shouldn't be a big problem.
