### ISSUE TITLE
When trying to move a unit or scroll the map, context menu is opened sometimes

### ISSUE THREAD

**Issue by abacabadabacaba** [singalen/wesnoth#28]
I try to move my finger as soon as I tap, but sometimes the game still detects a long tap and opens context menu, probably because of a lag. Perhaps a long tap should be interpreted as a right click only if the finger was released without moving.

**Comment by abacabadabacaba** [comment]
I updated to a new build (14), and now it seems that this bug is harder to reproduce, though still possible. I can reproduce it this way:
* Start the game.
* Select Multiplayer.
* Select Local Game.
* Select a big map, such as _5p — The Wilderlands_. Don't change other settings.
* Start the game.
* Tap to hide victory conditions.
* Try to drag the leader. At this point, the context menu is shown.

Also, as I tap to close the context menu, the path from the unit to the cell that I tapped is shown. This doesn't happen if I open the context menu normally (i.e. via a long tap). On the same map, sometimes the context menu opens when I tap the mini map, even though I try to release my finger as quickly as possible.

**Comment by singalen** [comment]
Thanks for the scenario!
What hardware are you using?
Will try how bad it is. Might leave it this way for some time, as there are more critical problems now.

**Comment by abacabadabacaba** [comment]
I'm using iPad 2 running iOS 9.3.5.

**Comment by singalen** [comment]
That's pretty dated, sorry. If it's bearable on iPad 2, on a faster hardware this should be fine.
You can get a better performance by disabling water animations, then all terrain animations.

**Comment by abacabadabacaba** [comment]
Actually, performance on iPad 2 is not that bad. There are minor lags right after starting a game, perhaps because some images and sounds are not yet cached at this point. It works fine afterwards.

For example, the context menu may pop up when selecting a unit for the first time after starting a scenario. After that, the context menu will not appear when trying to select units. Similarly, the context menu may appear when trying to scroll by tapping the mini map, but this usually happens if that part of a map was not visible before. In this case, the game may freeze for some time (more than a second in worst cases). But when scrolling to the same place again, it happens almost instantaneously.

I think that this is caused by the time it takes to load game resources, such as map tiles. If this time is somehow not counted when measuring the duration of a tap, this bug would not manifest itself.

**Comment by singalen** [comment]
Totally correct. I expect it to go completely after accelerated_rendering branch merge, so don't want to invest into this too much time. 
"when scrolling to the same place again" is an exact description of the weakness the workaround has now: https://github.com/singalen/wesnoth/blob/touch_interface_9/src/controller_base.cpp#L72

**Comment by abacabadabacaba** [comment]
Surprisingly, I can't reproduce this anymore using the new build (15).

**Comment by singalen** [comment]
So the fix got through. Great!
