### ISSUE TITLE
Save savegames to iCloud

### ISSUE THREAD

**Issue by singalen** [singalen/wesnoth#29]
Because why not.

**Comment by Simon-Laux** [comment]
How about Gamecenter integration for achievements, as far as GPL allows that?

**Comment by singalen** [comment]
Good point. #32.

**Comment by Simon-Laux** [comment]
iTunes integration for transferring wesnoth saves between computer and iPad would also be a nice feature

**Comment by singalen** [comment]
Closed and duplicated by #73
