### ISSUE TITLE
Grey/black bar where "Next unit" button should be

### ISSUE THREAD

**Issue by Simon-Laux** [singalen/wesnoth#30]
- there is grey bar in the top right corner
![image](https://user-images.githubusercontent.com/18725968/28851546-922470e6-7723-11e7-8c46-f91127d92739.png)
im on ipad 4  (9,7")

**Comment by singalen** [comment]
Wow. It's the intended place for a "Next unit" button. Looks like you got another theme applied.

**Comment by abacabadabacaba** [comment]
Hm, I have a black bar in the same place.

**Comment by Simon-Laux** [comment]
same (black) since update

**Comment by singalen** [comment]
Please try in the next build.
