### ISSUE TITLE
New app icon without transparency

### ISSUE THREAD

**Issue by Simon-Laux** [singalen/wesnoth#31]
transparency will be converted to black by ios.
![image](https://user-images.githubusercontent.com/18725968/28851687-a3758eec-7724-11e7-9a31-8d36accf8698.jpeg)
Thats why we need a new fancy app icon without transparency for iOS

**Comment by Simon-Laux** [comment]
I think just a background(like the wood from the titlescreen) for the logo would do it for now.
And all little bit scaling or positioning for the icon that it don't appear cropped by the round corners.

**Comment by Simon-Laux** [comment]
try this for the time being. maybe we come up with sth better at sometime.
![image](https://user-images.githubusercontent.com/18725968/28894129-24b5d66a-77d4-11e7-8a52-743c70cbd205.png)

**Comment by singalen** [comment]
Thank you very much! We need a variety of sizes, though - can you please make it? https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/ (we only need "App icon sizes")
Thanks again!

Round corners are cut by iOS and are inevitable. Please take note - or the problem with sword handles touching the edge will persist.

**Comment by Simon-Laux** [comment]
I tested round corners by roughly tracing the edges.( note: i edited this on my ipad with inkpad)
![image](https://user-images.githubusercontent.com/18725968/28898794-14120d24-77e8-11e7-9d97-f51100c865d9.png)
there is an website for resizing automatically😉: https://makeappicon.com
I quickly uploaded it there, here the results:
[image.zip](https://github.com/singalen/wesnoth/files/1195527/image.zip)

**Comment by singalen** [comment]
Thanks again!

**Comment by Simon-Laux** [comment]
your welcome.

(but I have to go to bed now its 01:21 here in germany...💤)

**Comment by Simon-Laux** [comment]
ps: looking forward to the new TestFlight update/release. happy coding/bug fixing

**Comment by Simon-Laux** [comment]
i belive we have solved this issue temporarily

**Comment by singalen** [comment]
Not yet. Please close issues when you see them fixed in a new build! ^)

**Comment by Simon-Laux** [comment]
ok, then i reopen it and close it when i see it fixed

**Comment by singalen** [comment]
Please try in the next build.
