### ISSUE TITLE
Add "Best possible enemy moves" button?

### ISSUE THREAD

**Issue by GuidoBartoli** [singalen/wesnoth#41]
I think an useful command that experienced players use very often on the PC version is "Best possible enemy moves" (CTRL+b) which shows the enemy influence and potential attacks on the map.
Since in the mobile version it is only accessible from the Actions menu, I think a good idea could be to add an helper button in top right corner below "Next unit" to provide an easy access to that.

**Comment by singalen** [comment]
I'm afraid there are too many buttons that different users want. For example, I use Ctrl-V, "all possible enemy moves", as I don't trust AI's judgement.
For now, I have a compromise: tapping an enemy unit shows its possible coverage.

**Comment by GuidoBartoli** [comment]
Yep, I'm doing it too as a workaround, but it is a bit tedious to do when you face many enemy units and you have to mentally remember all the individual ranges.
Could long-press on an enemy unit a nice solution to this issue and #46, too?

**Comment by singalen** [comment]
I'm rather thinking of a double-tap. Double-tap would do "most probable action". As for now, I only wanted quick recruiting action on a castle tile.

**Comment by GuidoBartoli** [comment]
Yep, double-tap could be nice for recruiting!

**Comment by singalen** [comment]
Created #66 for this function.
