### ISSUE TITLE
Keyboard panel pops up when not needed

### ISSUE THREAD

**Issue by GuidoBartoli** [singalen/wesnoth#42]
In many windows where a textual search is present (Multiplayer, Load, Recall, ...) the iOS keyboard panel is always shown even if the focus in not on text field. The user has to manually close is to see the whole screen, and if the window is closed without hiding the keyboard panel, it still remains on screen until it is not manually hidden (it blocks half screen).
![img_0544](https://user-images.githubusercontent.com/16103676/29435243-7f42a1a2-83a6-11e7-8ec9-72f913e87132.jpg)

**Comment by abacabadabacaba** [comment]
Same as #3.

**Comment by GuidoBartoli** [comment]
Yeah, sorry, I did not notice that!
