### ISSUE TITLE
Strange graphical glitches

### ISSUE THREAD

**Issue by GuidoBartoli** [singalen/wesnoth#43]
Only in one occasion, the graphical interface totally messed up: scrolling the map made sprite traces appearing all over the screen, while the right status panel was completely unusable. Unfortunately, I could not reproduce this error, it only happened once, but to resolve it I had to uninstall and re-install the latest beta again.
![img_0546](https://user-images.githubusercontent.com/16103676/29435290-bbc47196-83a6-11e7-86cb-ea1a0add2f74.jpg)

**Comment by singalen** [comment]
Wow, good one. I'm afraid though that we'll have to have a way to reproduce it in order to fix it.

**Comment by GuidoBartoli** [comment]
Ok, I will add updates here if I can reproduce it!
