### ISSUE TITLE
Question mark in the load panel

### ISSUE THREAD

**Issue by GuidoBartoli** [singalen/wesnoth#45]
When a game has to be loaded as soon as Wesnoth is launched, selecting it cause a _red question mark_ (attached screenshot) to appear in the lower left corner.
When the load panel is closed and reopened, this problem disappears and the correct hero image is shown. I think this is some missed initialization during the first the time the Load panel is displayed.
![img_0551](https://user-images.githubusercontent.com/16103676/29435713-58cdd60c-83a8-11e7-9e65-06e8945d80d5.jpg)

**Comment by singalen** [comment]
Thanks for report, but there's so much critical work, like iPhone support.
