### ISSUE TITLE
Add an easy way to see enemy unit's defense rating

### ISSUE THREAD

**Issue by abacabadabacaba** [singalen/wesnoth#46]
In the desktop version of Battle for Wesnoth, I can select an enemy unit and then hover the cursor over different hexes to quickly see its defense rating in those hexes. This is very useful when planning where to place your units so that the enemy doesn't have a good place to attack them from. In iOS version, this doesn't work: if I try to drag an enemy unit, it will scroll the map instead.

**Comment by ghost** [comment]
It's cool they are there, only one has to be really quick handed to use it. Useless trivia, when near the border of the map is easy to get unit defenses in tiles in opposite direction to the nearest map border.

![img_0085](https://user-images.githubusercontent.com/3533348/31307285-382eadbe-ab61-11e7-8790-cb055ca912ad.PNG)

**Comment by singalen** [comment]
Good point, you convinced me.
Will enable the piece that drags the enemy unit back. 
Thanks!

**Comment by singalen** [comment]
Now you can "control" enemy unit dragging it.
Might look like a bug to someone, but this issue proves it's a feature!
