### ISSUE TITLE
Hide unnecessary preferences 

### ISSUE THREAD

**Issue by singalen** [singalen/wesnoth#5]
* «Host network game» in «Multiplayer» window.
* Display/Scroll speed
* Crash in «Server executable» preference.
* "Turn off music when inactive"
* what else?..

**Comment by Simon-Laux** [comment]
the path change buttons or the paths all together
![image](https://user-images.githubusercontent.com/18725968/28851597-fe494080-7723-11e7-99de-356da89bfce9.png)
also in the library tab is nothing

**Comment by singalen** [comment]
removed
