### ISSUE TITLE
1.13.8dev: Main menu shifted to left

### ISSUE THREAD

**Issue by GuidoBartoli** [singalen/wesnoth#52]
I just upgraded Wesnoth to the latest TestFlight version, but, as soon as the game launches, the main is shifted to the left and the usual tips are not displayed.
Here is the screenshot:
![img_0560](https://user-images.githubusercontent.com/16103676/30244519-8a519294-95bf-11e7-9498-190fea16e8f0.PNG)

**Comment by singalen** [comment]
Thanks for the report, that's intended - a leftover from iPhone work. On iPhone, it's going to take at least half a screen.
