### ISSUE TITLE
App gets closed when tapping `Name` after tapping `Campaigns`.

### ISSUE THREAD

**Issue by ghost** [singalen/wesnoth#54]
# Abstract

App gets closed when tapping `Name` after tapping `Campaigns`.

## Program version

`1.13.9`.

## TestFlight build number

`16`.

## Device type

Apple iPad `MD523TY/A`.

## Supervisor information

iOS 10.3.3 14G60 (vanilla).

## Steps to reproduce

* Open Wesnoth App. App shows title. App shows specific load messaging.
  App shows splash with map, UI and music.
* Tap `Campaigns`. Campaigns menu opens.
* Tap `Name` under the sub `Sort by:` UI control, as in
  `ORDER BY campaign.name`. **App gets closed**.

**Comment by singalen** [comment]
Fixed by making sorting case-sensitive. #2094

**Comment by ghost** [comment]
Fair enough good for now! It'll get fixed by upstream, eventually. Thank you!
