### ISSUE TITLE
125% and 150% font size support

### ISSUE THREAD

**Issue by singalen** [singalen/wesnoth#56]
* Increase font to 125%.
* increase top bar to fit text
* increase buttons
* adjust sidebar elements to fit:
** level is not visible
** HP, XP, class, alignment are cut on the bottom
* There's a big hole between class, race and attacks. At the same time, 3 attacks won't fit in to sidebar.

**Comment by ghost** [comment]
I think the _3 attacks not fitting_ issue is a must fix. Similarly, _magical_ attack attribute of the _missile_ attack of _Mage_ is not fitting.

**Comment by ghost** [comment]
For iPad 4 `MD523TY/A` the previous default font size used in build 16 was more appropriate than the default 125% of build 25. I got some screenshots. Because display configuration works very good on this, no worries. I understand it is an old device now.

**Comment by singalen** [comment]
Can you please share the screenshots?
Thanks!

**Comment by ghost** [comment]
This was build 16 default font size and I didn't even ever wandered display preferences while it was installed:

![img_0086](https://user-images.githubusercontent.com/3533348/31472636-295380d4-aef0-11e7-8cf5-256c95c07d96.PNG)

This was build 25 default font size and I found it excessive large, cropping in many widgets, made me investigate display preferences to change them and see how good changes:

![img_0087](https://user-images.githubusercontent.com/3533348/31472697-8300fb0c-aef0-11e7-809a-7b7dd0073e47.PNG)

http://hwstats.unity3d.com/mobile/device-ios.html 😔

**Comment by singalen** [comment]
Sorry for that. I believe font must be bigger, especially for iPad Mini (I have one. Shame on me - I care for myself only).
This default font size should definitely consider physical display size. Plus, a sidebar MUST adjust to 125% and even 150% font size.

**Comment by singalen** [comment]
Bigger fonts support was removed upstream.
