### ISSUE TITLE
Hide and forever enable «pause music on focus loss»

### ISSUE THREAD

**Issue by singalen** [singalen/wesnoth#6]

**Comment by singalen** [comment]
done

**Comment by ghost** [comment]
I don't know what _pause music on focus loss_ is.

I have a note stating _warn `singalen/wesnoth` music fades out too much abruptly when "iPad screen going idle and sleepy", compared to other game apps_.

Is it the same issue?

**Comment by singalen** [comment]
Nope, the opposite.

"Pause music on focus loss" means "pause music when user switches to another application". Makes sense on desktop, and, for me, even more on a tablet.

Can you create a new issue please?
I think  I should enable the setting back in the next TestFlight build and test it.
