### ISSUE TITLE
Double-tap as a "default action"

### ISSUE THREAD

**Issue by singalen** [singalen/wesnoth#66]
Some keyboard shortcuts have no easy equivalents in touch UI.
Proposal: double-tap should:
* on an empty castle cell - invoke a recruiting dialog;
* on other empty cell - ???
* on any enemy unit - show all enemies' possible moves;
* on an own unit - ??? show context menu? Show description?

**Comment by GuidoBartoli** [comment]
These are my proposals:
- **on an empty castle cell** - invoke a recruiting dialog
- **on a own leader on castle cell** - invoke a recall dialog?
- **on an other empty cell** - show enemy possible moves
- **on an generic unit** - show unit description

**Comment by rgilsoul** [comment]
A double click should open up an action menu next to the unit including basic information about the unit or terrain and a menu of basic actions available for that unit or square.  That was how it was traditionally in other versions as I recall.  It was a lot faster than the current long hold on a unit or square to bring up the same.

**Comment by singalen** [comment]
@rgilsoul 
I'm seriously considering the idea that double-tap should open a menu, and long-tap do some optional action you can live without.
Sorry, when did the context menu have unit and terrain information? Or is it a new suggestion?

**Comment by GuidoBartoli** [comment]
I agree with @rgilsoul, tap-and-hold is not so convenient for such frequent actions in the game.

**Comment by rgilsoul** [comment]
I think the bit about the context menu having info might be something I misremembered from one of those older ports of Wesnoth.  I think maybe that only came up when a person hit unit info or something.  I have been wishing I could look at the older ports so I could remember exactly what they looked like.

**Comment by singalen** [comment]
Well, now double-tap opens a menu. A classic choice.
Closing this for now, but please feel free to comment in #44.
