### ISSUE TITLE
Keyboard Coverup

### ISSUE THREAD

**Issue by rgilsoul** [singalen/wesnoth#68]
When I try to rename a unit, the keyboard covers up the text entry box on the UI.

**Comment by singalen** [comment]
Cannot reproduce on the dev build.
A new build is coming soon.

What is your hardware? Can you attach a screenshot please?
Thanks!

**Comment by rgilsoul** [comment]
So sorry.  Had some problems with my email account and just saw that this had been referenced.  I will get right on it and hopefully the problem has disappeared.

**Comment by singalen** [comment]
No worries! Opensource is slow at (most) times :)

**Comment by rgilsoul** [comment]
Well, that was a fast response.  To properly test this I had to have a slower response as I had to download the latest update.  It works fine now.  I had the problem in other games for a brief while, and I think it had to do with the keyboard changes they came out witha few months ago, but the problem is all gone now.

**Comment by singalen** [comment]
Great, thanks!
