### ISSUE TITLE
Sleep for Rest of Turn Status

### ISSUE THREAD

**Issue by rgilsoul** [singalen/wesnoth#69]
It would be nice to have a toggle to remove a unit from the "next" unit list of units that still have an action abailable if we are satisfied with its current state.  So, if I am happy with where a unit is and no longer want to look at it, I hit a zzzz button, (like in Panzer Corps), and until the next turn that unit will show as not active unless I manually select it or say oress a button deselecting all sleeping units.  

This was in one of the Wesnoths on the ipad a long time ago but the most recent HD version before the current release did not have it, and it was a oain when there were lots of units on the board.  Perhaps I have just missed something, but I do not see it.

**Comment by singalen** [comment]
Indeed, there's no button for that. There is a menu item though.

While the function is definitely useful, we cannot put up a button for every useful action out there, even if it's used multiple times each turn. 
Here are a few I can name right now: "Next unit", this "Zzz", "Show (best/all) enemy moves", "Undo".

This might work if we completely rework the mobile UI, which I'd love to do some day. What I envision is something like Majesty mobile UI, with expandable panels in a corners.

**Comment by rgilsoul** [comment]
I was not suggesting that we necessarily have a button.  I meant a command that will toggle a unit's status as available to move.  If it is unavailable, then technically the unit can move, but when you hit next unit, that unit will no longer show up as being able to move.  That way, you move or toggle as moved all your units until you have no more units to move and no longer see the units that you chose to leave as they were or which made only oartial moves,   I presume it could appear in the actions list if a button could not be used.

I like the Majesty idea, by the way, but I can see how that would be a long way off.

**Comment by singalen** [comment]
Added in dev.
