### ISSUE TITLE
Labels are manipulable.

### ISSUE THREAD

**Issue by ghost** [singalen/wesnoth#78]
Labels are manipulable by swiping any part of the displayed part of the map when focusing near the map borders. I will add self explaining screenshots later.

**Comment by ghost** [comment]
These...
![img_0143](https://user-images.githubusercontent.com/3533348/34358558-11cb2d62-ea51-11e7-8e79-6b08cd928b0a.PNG)

Swiping a bit...
![img_0144](https://user-images.githubusercontent.com/3533348/34358568-27805e0c-ea51-11e7-9101-6b697c7d46c7.PNG)

Cheers & Regards,

**Comment by singalen** [comment]
Upstream bug: https://github.com/wesnoth/wesnoth/issues/2333
