### ISSUE TITLE
Iterating the tabs under Preferences causes irregular display issues.

### ISSUE THREAD

**Issue by ghost** [singalen/wesnoth#88]
Running Wesnoth `1.14` TestFlight `38`.

This is unimportant, but it is happening:

Selecting a tab A (`General`, `Display`, `Sound`, `Multiplayer`, `Advanced`) in the `Preferences` menu will show it with a slim vertical yellow bar and a blue gradient background.

Selecting another tab B will show B with a slim vertical yellow bar and a blue gradient background. Background in A will become either black or a darker blue gradient.

I tried to reproduce it in macOS to check if it is affected too, but I couldn't reproduce the issue there.

**Comment by singalen** [comment]
Thanks! Do you mind if I close it? I'm afraid OpenGL version will be released before anyone decides to look into this.

**Comment by ghost** [comment]
No worries, do whatever you find more convenient.

**Comment by singalen** [comment]
ok, thanks!
