### ISSUE TITLE
Eastern Invasion (Captured) in IoS: cannot move freed prisoners -- instant campaign end (death)

### ISSUE THREAD

**Issue by SwissGuy19** [singalen/wesnoth#99]
Version: IoS 1.14.4
Campaign: Eastern Invasion, scenario "Captured" (it's a mainline campaign, so far as I know)

Issue: when my disguised Escapee opens a prison cell to make my other units available, they become "my" units, but they are all shown with a Red dot above (as in, their turn has ended and they cannot do any further actions). The same thing happens to Dacyn, Gweddry and Owaec. Therefore, I cannot move the heroes out of harm's way, nor can I use the freed prisoners to attack, and the only possible action is "end turn" once I have moved the three escapees.

Since the heroes are all in open space with several nearby Orc Warriors and Level 2 trolls, once they became "my" units, the monsters turn hostile and attack them. Dacyn promptly gets slaughtered and the scenario ends. Hence it is impossible to progress further.

I have read elsewhere that this is a bug, and that the intent is that I should get one turn to try to move the heroes to safety by moving and sacrificing some of the freed prisoners.

I would be grateful if you would fix this! I believe it has been an issue for some time now based on some comments on forums, but I cannot find any evidence that this has been entered here as a bug report.

**Comment by ln-zookeeper** [comment]
Looking at the WML, my **guess** would be that on iOS units don't get full movement points back when their side ends turn; when the prisoners are released, they are simply changed from side 3 to player side 1, which normally means they immediately do have full movement and attacks, but **maybe** that's not true on iOS for some reason.

**Comment by singalen** [comment]
Thanks for the report and sorry for the bug. Indeed, there is a slight difference in a way iOS version counts the moves. Will address it in 1.14.6 release.

**Comment by SwissGuy19** [comment]
Cool. What is the approximate timeframe for 1.14.6, please?

**Comment by singalen** [comment]
Fix is coming in the next release.
